ALTER TABLE IF EXISTS learning_goals
  ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS reward_points INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS completed_at TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS target_lessons INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS current_lessons INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS target_quizzes INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS current_quizzes INTEGER DEFAULT 0;
